version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: farpost
      POSTGRES_USER: farpost_user
      POSTGRES_PASSWORD: farpost_password

  web:
    build: .
    command: >
      sh -c "
      /wait-for-postgres.sh db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py populate_ads &&
      echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin') if not User.objects.filter(username='admin').exists() else print('Superuser already exists')\" | python manage.py shell &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
